import { 
  LucideIcon, 
  UserRound,
  LogIn,
  Command,
  Menu,
  Database,
  UserRoundCheck,
  Sun,
  Moon,
  Laptop,
  MoreVertical,
  Loader2,
  Trash,
  Car,
  NotepadText,
  PaintBucket,
  LibrarySquare,
  BarChart3,
  Image,
  Eye,
  CircuitBoard,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  user: UserRound,
  logIn: LogIn,
  logo: Command,
  menu: Menu,
  database: Database,
  auth: UserRoundCheck,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  ellipsis: MoreVertical,
  spinner: Loader2,
  trash: Trash,
  car: Car,
  notepad: NotepadText,
  color: PaintBucket,
  category: LibrarySquare,
  chart: BarChart3,
  image: Image,
  eye: Eye,
  circuitBoard: CircuitBoard,
};